server:
    port: 8081
spring:
    application:
        name: service-b
    cloud:
        nacos:
            server-addr: 127.0.0.1:8848
            discovery:
                username: nacos
                password: nacos
            config:
                import-check:
                    enabled: false
            # config:
            #     server-addr: localhost:8848
            #     file-extension: yaml
            #     namespace: dep
